### ISSUE TITLE
TG2-VALIDATION_MONTH_NOTSTANDARD

### ISSUE THREAD

**Issue by ArthurChapman** [tdwg/bdq#146] opened 2018-08-26 10:36 UTC
Field | Value |
| ----- | ----- |
| **GUID** |   |
| **Label** | VALIDATION_MONTH_NOTSTANDARD |
| **Output Type** | Validation |
| **Resource Type** | SingleRecord |
| **Darwin Core Class** | Event |
| **Information Elements** | dwc:month |
| **Fail Description** | The value of dwc:month is not an integer between 1 and 12 inclusive |
| **Pass Description** | The value of dwc:month is an integer between 1 and 12 inclusive |
| **Dimension** | Time |
| **Data Quality Dimension** | Conformance |
| **Term-Actions** | MONTH_NOTSTANDARD |
| **Warning Type** | Invalid |
| **Example** | dwc:month="Dec" |
| **Source** | TDWG2018 DQIG Meeting |
| **References** |  |
| **Example Implementations (Mechanisms)** |  |
| **Link to Specification Source Code** |   |
| **Notes** |  |
| **Test Prerequisites** | The field dwc:month is not EMPTY. |

**Comment by ArthurChapman** [comment] 2018-08-30 00:03
We have changed the description of this from "is not an unambiguous value" to "is not an integer between 1 and 12, inclusive.

**Comment by chicoreus** [comment] 2018-08-30 05:53
Discussed 5:30 Thursday TDWG 2018.  Duplicate of #126

**Closed by chicoreus** 2018-08-30 05:53 UTC
Labels: CONFIRMED, Conformance, TG2, TIME, Validation

**Comment by Tasilee** [comment] 2024-02-22 03:26
Fix TestType, Description, Information Elements, Parameters, Source Authority, Expected Response and examples to conform to current template.

**Comment by Tasilee** [comment] 2024-02-22 03:28
Change NAME of test
